package pe.edu.sistemas.sisrepweb.domain;
// Generated 19/12/2017 12:58:19 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name = "asistencia", catalog = "modelogeneralfisi")
public class Asistencia implements java.io.Serializable {

	private Integer idasistencia;
	private HorarioClase horarioClase;
	private Date asistenciaHoraIngreso;
	private Date asistenciaHoraSalida;
	private String asistenciaTema;
	private Date asistenciaFecha;
	private String asistenciaObservacion;
	private String asistenciaTipoMarca;
	private Integer motivoIdmotivo;

	public Asistencia() {
	}

	public Asistencia(HorarioClase horarioClase, Date asistenciaHoraIngreso, Date asistenciaHoraSalida,
			String asistenciaTema, Date asistenciaFecha, String asistenciaObservacion) {
		this.horarioClase = horarioClase;
		this.asistenciaHoraIngreso = asistenciaHoraIngreso;
		this.asistenciaHoraSalida = asistenciaHoraSalida;
		this.asistenciaTema = asistenciaTema;
		this.asistenciaFecha = asistenciaFecha;
		this.asistenciaObservacion = asistenciaObservacion;
	}

	public Asistencia(HorarioClase horarioClase, Date asistenciaHoraIngreso, Date asistenciaHoraSalida,
			String asistenciaTema, Date asistenciaFecha, String asistenciaObservacion, String asistenciaTipoMarca,
			Integer motivoIdmotivo) {
		this.horarioClase = horarioClase;
		this.asistenciaHoraIngreso = asistenciaHoraIngreso;
		this.asistenciaHoraSalida = asistenciaHoraSalida;
		this.asistenciaTema = asistenciaTema;
		this.asistenciaFecha = asistenciaFecha;
		this.asistenciaObservacion = asistenciaObservacion;
		this.asistenciaTipoMarca = asistenciaTipoMarca;
		this.motivoIdmotivo = motivoIdmotivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDASISTENCIA", unique = true, nullable = false)
	public Integer getIdasistencia() {
		return this.idasistencia;
	}

	public void setIdasistencia(Integer idasistencia) {
		this.idasistencia = idasistencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HORARIO_CLASE_IDHORARIO_CLASE", nullable = false)
	public HorarioClase getHorarioClase() {
		return this.horarioClase;
	}

	public void setHorarioClase(HorarioClase horarioClase) {
		this.horarioClase = horarioClase;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ASISTENCIA_HORA_INGRESO", nullable = false, length = 8)
	public Date getAsistenciaHoraIngreso() {
		return this.asistenciaHoraIngreso;
	}

	public void setAsistenciaHoraIngreso(Date asistenciaHoraIngreso) {
		this.asistenciaHoraIngreso = asistenciaHoraIngreso;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ASISTENCIA_HORA_SALIDA", nullable = false, length = 8)
	public Date getAsistenciaHoraSalida() {
		return this.asistenciaHoraSalida;
	}

	public void setAsistenciaHoraSalida(Date asistenciaHoraSalida) {
		this.asistenciaHoraSalida = asistenciaHoraSalida;
	}

	@Column(name = "ASISTENCIA_TEMA", nullable = false, length = 100)
	public String getAsistenciaTema() {
		return this.asistenciaTema;
	}

	public void setAsistenciaTema(String asistenciaTema) {
		this.asistenciaTema = asistenciaTema;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ASISTENCIA_FECHA", nullable = false, length = 10)
	public Date getAsistenciaFecha() {
		return this.asistenciaFecha;
	}

	public void setAsistenciaFecha(Date asistenciaFecha) {
		this.asistenciaFecha = asistenciaFecha;
	}

	@Column(name = "ASISTENCIA_OBSERVACION", nullable = false, length = 65535)
	public String getAsistenciaObservacion() {
		return this.asistenciaObservacion;
	}

	public void setAsistenciaObservacion(String asistenciaObservacion) {
		this.asistenciaObservacion = asistenciaObservacion;
	}

	@Column(name = "ASISTENCIA_TIPO_MARCA", length = 25)
	public String getAsistenciaTipoMarca() {
		return this.asistenciaTipoMarca;
	}

	public void setAsistenciaTipoMarca(String asistenciaTipoMarca) {
		this.asistenciaTipoMarca = asistenciaTipoMarca;
	}

	@Column(name = "MOTIVO_IDMOTIVO")
	public Integer getMotivoIdmotivo() {
		return this.motivoIdmotivo;
	}

	public void setMotivoIdmotivo(Integer motivoIdmotivo) {
		this.motivoIdmotivo = motivoIdmotivo;
	}

}
