package pe.edu.sistemas.sisrepweb.domain;
// Generated 14/12/2017 01:55:45 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Escuela generated by hbm2java
 */
@Entity
@Table(name = "ESCUELA", catalog = "modelogeneralfisi")
public class Escuela implements java.io.Serializable {

	private Integer idescuela;
	private int facultadIdfacultad;
	private String escuelaNombre;

	public Escuela() {
	}

	public Escuela(int facultadIdfacultad, String escuelaNombre) {
		this.facultadIdfacultad = facultadIdfacultad;
		this.escuelaNombre = escuelaNombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDESCUELA", unique = true, nullable = false)
	public Integer getIdescuela() {
		return this.idescuela;
	}

	public void setIdescuela(Integer idescuela) {
		this.idescuela = idescuela;
	}

	@Column(name = "FACULTAD_IDFACULTAD", nullable = false)
	public int getFacultadIdfacultad() {
		return this.facultadIdfacultad;
	}

	public void setFacultadIdfacultad(int facultadIdfacultad) {
		this.facultadIdfacultad = facultadIdfacultad;
	}

	@Column(name = "ESCUELA_NOMBRE", nullable = false, length = 45)
	public String getEscuelaNombre() {
		return this.escuelaNombre;
	}

	public void setEscuelaNombre(String escuelaNombre) {
		this.escuelaNombre = escuelaNombre;
	}

}
