package pe.edu.sistemas.sisrepweb.domain;
// Generated 05/01/2018 04:27:09 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HorarioClase generated by hbm2java
 */
@Entity
@Table(name = "HORARIO_CLASE")
public class HorarioClase implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer idhorarioClase;
	private Docente docente;
	private Grupo grupo;
	private Date horaInicio;
	private Date horaFin;
	private String aula;
	private Integer dia;
	private String horarioClaseTipo;
	private String horarioClasePeriodo;
	private Integer aulaIdaula;
	private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);

	public HorarioClase() {
	}

	public HorarioClase(Docente docente, Grupo grupo, String horarioClaseTipo, String horarioClasePeriodo) {
		this.docente = docente;
		this.grupo = grupo;
		this.horarioClaseTipo = horarioClaseTipo;
		this.horarioClasePeriodo = horarioClasePeriodo;
	}

	public HorarioClase(Docente docente, Grupo grupo, Date horaInicio, Date horaFin, String aula, Integer dia,
			String horarioClaseTipo, String horarioClasePeriodo, Integer aulaIdaula, Set<Asistencia> asistencias) {
		this.docente = docente;
		this.grupo = grupo;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.aula = aula;
		this.dia = dia;
		this.horarioClaseTipo = horarioClaseTipo;
		this.horarioClasePeriodo = horarioClasePeriodo;
		this.aulaIdaula = aulaIdaula;
		this.asistencias = asistencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDHORARIO_CLASE", unique = true, nullable = false)
	public Integer getIdhorarioClase() {
		return this.idhorarioClase;
	}

	public void setIdhorarioClase(Integer idhorarioClase) {
		this.idhorarioClase = idhorarioClase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCENTE_IDDOCENTE", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRUPO_IDGRUPO", nullable = false)
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_INICIO", length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_FIN", length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "AULA", length = 45)
	public String getAula() {
		return this.aula;
	}

	public void setAula(String aula) {
		this.aula = aula;
	}

	@Column(name = "DIA")
	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

	@Column(name = "HORARIO_CLASE_TIPO", nullable = false, length = 45)
	public String getHorarioClaseTipo() {
		return this.horarioClaseTipo;
	}

	public void setHorarioClaseTipo(String horarioClaseTipo) {
		this.horarioClaseTipo = horarioClaseTipo;
	}

	@Column(name = "HORARIO_CLASE_PERIODO", nullable = false, length = 10)
	public String getHorarioClasePeriodo() {
		return this.horarioClasePeriodo;
	}

	public void setHorarioClasePeriodo(String horarioClasePeriodo) {
		this.horarioClasePeriodo = horarioClasePeriodo;
	}

	@Column(name = "AULA_IDAULA")
	public Integer getAulaIdaula() {
		return this.aulaIdaula;
	}

	public void setAulaIdaula(Integer aulaIdaula) {
		this.aulaIdaula = aulaIdaula;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horarioClase")
	public Set<Asistencia> getAsistencias() {
		return this.asistencias;
	}

	public void setAsistencias(Set<Asistencia> asistencias) {
		this.asistencias = asistencias;
	}

}
