package pe.edu.sistemas.sisrepweb.domain;
// Generated 26/09/2017 04:31:47 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plan generated by hbm2java
 */
@Entity
@Table(name = "PLAN", catalog = "modeloGeneralFisi")
public class Plan implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer idplan;
	private int escuelaIdescuela;
	private String planNombre;
	private Set<CursoBase> cursoBases = new HashSet<CursoBase>(0);

	public Plan() {
	}

	public Plan(int escuelaIdescuela, String planNombre) {
		this.escuelaIdescuela = escuelaIdescuela;
		this.planNombre = planNombre;
	}

	public Plan(int escuelaIdescuela, String planNombre, Set<CursoBase> cursoBases) {
		this.escuelaIdescuela = escuelaIdescuela;
		this.planNombre = planNombre;
		this.cursoBases = cursoBases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPLAN", unique = true, nullable = false)
	public Integer getIdplan() {
		return this.idplan;
	}

	public void setIdplan(Integer idplan) {
		this.idplan = idplan;
	}

	@Column(name = "ESCUELA_IDESCUELA", nullable = false)
	public int getEscuelaIdescuela() {
		return this.escuelaIdescuela;
	}

	public void setEscuelaIdescuela(int escuelaIdescuela) {
		this.escuelaIdescuela = escuelaIdescuela;
	}

	@Column(name = "PLAN_NOMBRE", nullable = false, length = 45)
	public String getPlanNombre() {
		return this.planNombre;
	}

	public void setPlanNombre(String planNombre) {
		this.planNombre = planNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plan")
	public Set<CursoBase> getCursoBases() {
		return this.cursoBases;
	}

	public void setCursoBases(Set<CursoBase> cursoBases) {
		this.cursoBases = cursoBases;
	}

}
