package pe.edu.sistemas.sisrepweb.domain;
// Generated 19/12/2017 12:58:19 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plan generated by hbm2java
 */
@Entity
@Table(name = "PLAN", catalog = "modelogeneralfisi")
public class Plan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7431429449429081034L;
	private Integer idplan;
	private Escuela escuela;
	private String planNombre;
	private Set<CursoBase> cursoBases = new HashSet<CursoBase>(0);

	public Plan() {
	}

	public Plan(Escuela escuela, String planNombre) {
		this.escuela = escuela;
		this.planNombre = planNombre;
	}

	public Plan(Escuela escuela, String planNombre, Set<CursoBase> cursoBases) {
		this.escuela = escuela;
		this.planNombre = planNombre;
		this.cursoBases = cursoBases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPLAN", unique = true, nullable = false)
	public Integer getIdplan() {
		return this.idplan;
	}

	public void setIdplan(Integer idplan) {
		this.idplan = idplan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESCUELA_IDESCUELA", nullable = false)
	public Escuela getEscuela() {
		return this.escuela;
	}

	public void setEscuela(Escuela escuela) {
		this.escuela = escuela;
	}

	@Column(name = "PLAN_NOMBRE", nullable = false, length = 45)
	public String getPlanNombre() {
		return this.planNombre;
	}

	public void setPlanNombre(String planNombre) {
		this.planNombre = planNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plan")
	public Set<CursoBase> getCursoBases() {
		return this.cursoBases;
	}

	public void setCursoBases(Set<CursoBase> cursoBases) {
		this.cursoBases = cursoBases;
	}

}
